# Generated by Django 5.2.3 on 2025-06-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='debut_year',
            field=models.DateField(),
        ),
    ]
