# Generated by Django 5.2.3 on 2025-06-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artist_debut_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='debut_year',
            field=models.IntegerField(),
        ),
    ]
